spring.application.name=mod3
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=Nik0las!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true